### ISSUE TITLE
你好 ，启动完“启动.bat”后闪退，截图如下

### ISSUE THREAD

**Issue by 744184755** [localhost02/Taobao_order_robot#11]
请问应该怎么办呀？

**Comment by 744184755** [comment]
![Snipaste_2019-04-15_15-36-42](https://user-images.githubusercontent.com/36415334/56114912-c5cf3380-5f94-11e9-99c0-fd7e7a622dc6.png)

**Comment by 744184755** [comment]
哇， 修改了False大小写问题

**Comment by 744184755** [comment]
目前挂在服务器上，异地登陆，导致淘宝登陆滑块都刷新异常：哎呀，出错了，点击刷新再来一次(error:EPgHmf)，使用扫码登陆好像就无效

**Comment by localhost02** [comment]
em……淘宝页面做了变动导致的吗？由于最近较忙，目前有一段时间没有维护该项目了

**Comment by lyxlty** [comment]
@localhost02 @744184755 同出现这样的问题：导致淘宝登陆滑块都刷新异常：哎呀，出错了，点击刷新再来一次，请问下解决了吗？ 谢谢！

**Comment by 744184755** [comment]
没办法解决  淘宝检测到机器人就不给你登录了

**Comment by 744184755** [comment]
> @localhost02 @744184755 同出现这样的问题：导致淘宝登陆滑块都刷新异常：哎呀，出错了，点击刷新再来一次，请问下解决了吗？ 谢谢！

没办法解决 淘宝检测到机器人就不给你登录了
