### ISSUE TITLE
你好这个问题应该怎么解决呀？

### ISSUE THREAD

**Issue by 744184755** [localhost02/Taobao_order_robot#13]
![Snipaste_2019-04-16_16-11-49](https://user-images.githubusercontent.com/36415334/56193107-79522980-6062-11e9-907b-925003a9988a.png)

**Comment by 744184755** [comment]
在csdn登陆的时候出现问题

**Comment by lyxlty** [comment]
@localhost02 @744184755 你好，请问下 # 4.根据订单id组合url，请求订单对应留言
            order_message = json.loads(self.__session.get(self.__message_path + order_id).text)['tip']这行代码是不是有错？怎么留言解析不出来
![image](https://user-images.githubusercontent.com/11659778/56785405-9c7d9580-6827-11e9-8dbd-99e8aff0b029.png)
